src/lib/blob_manager.cpp, src/lib/homeobject_impl.hpp, src/lib/homestore/homeobject.hpp, src/lib/homestore/shard_manager.cpp, src/lib/memory/homeobject.hpp, src/lib/memory/shard_manager.cpp, src/lib/shard_manager.cpp
get_shard should be common among homestore version and memory version.
=> SDSTOR-11612 get_shard

src/lib/memory/homeobject.hpp
=> Remove extra layer of indirection.

conanfile.py, src/include/homeobject/blob_manager.hpp, src/include/homeobject/common.hpp, src/lib/blob_manager.cpp, src/lib/blob_route.hpp, src/lib/homeobject_impl.hpp, src/lib/homestore_backend/CMakeLists.txt, src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/index_kv.cpp, src/lib/homestore_backend/index_kv.hpp, src/lib/homestore_backend/replication_state_machine.cpp, src/lib/homestore_backend/tests/bits_generator.hpp, src/lib/homestore_backend/tests/test_home_object.cpp, src/lib/memory_backend/mem_blob_manager.cpp, src/lib/memory_backend/mem_homeobject.hpp
Create index table with key as BlobRoute(shard id, blobid) and value as MultiBlkId.
Do recovery of index table and connect with pg superblk ->index table uuid.
Do put with blob header and metadata. Allow request with a length from a particular offset.
Test create some pg's, shards and do put and get blob. Restart and then again verify with get with random offset and length.
=> Implement put and get apis

src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/tests/test_hs_homeobject.cpp
Fix user key hash calucation by taking the actual user key bytes. 
Test code fix to use resize.
=> Fix user key hash calculation.

src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/hs_shard_manager.cpp, src/lib/homestore_backend/tests/CMakeLists.txt, src/lib/tests/fixture_app.cpp, src/lib/tests/fixture_app.hpp
=> hs_homeobject: Persist SvcId after FORMAT for recovery to _our_id.

src/include/homeobject/blob_manager.hpp, src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/index_kv.cpp, src/lib/homestore_backend/replication_state_machine.cpp, src/lib/homestore_backend/tests/hs_blob_tests.cpp
referring the discussion [here](https://ebay-eng.slack.com/archives/CAVQXEAKS/p1698161973016819), we do not need tombstone, and just remove the blob from btree when it is deleted
=> Implement blob del API

src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/index_kv.cpp, src/lib/homestore_backend/tests/hs_blob_tests.cpp, src/lib/homestore_backend/tests/hs_shard_tests.cpp, src/lib/memory_backend/mem_blob_manager.cpp, src/lib/tests/BlobManagerTest.cpp
This is not _critical_ as SM treats both errors equally (UNKNOWN_BLOB and INDEX_ERROR). But we should be correct about what we pass back to the client application.
=> Delete BLOB should be idempotent.

src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/index_kv.cpp
since we add recover dependency logic in HS, this PR adopt this functionality and simplify the recover logic in homeobject
=> Adopt recovery order of HS metaservice

src/lib/homeobject_impl.cpp, src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/hs_shard_manager.cpp, src/lib/homestore_backend/index_kv.cpp
adapt homestore latest changes to disable copy superblock
=> adapt homestore superblock new interface

conanfile.py, src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/index_kv.cpp, src/lib/homestore_backend/tests/hs_blob_tests.cpp, src/lib/homestore_backend/tests/hs_shard_tests.cpp, src/lib/tests/fixture_app.cpp, src/lib/tests/fixture_app.hpp, test_package/test_package.cpp
If put fails and returns existing valid pba, then ignore. If key not found for delete, then ignore. If key exists and already tomebestone, then ignore. If key exists and valid pba then do the free blks.
=> Make delete and put api idempotent in recovery case.

conanfile.py, src/lib/homestore_backend/hs_homeobject.cpp
make HO app weak ptr to avoid circular shared ptr dependency
=> Shutdown bug

conanfile.py
Given that there are some new commits since 1.0.12, let bump to 1.0.13 to distinguish them.
=> Upgrade to 1.0.13

conanfile.py, src/lib/homestore_backend/hs_http_manager.cpp
Http_server should be started in SM, otherwise sm will crash due to setup twice.
=> Remove http_server start logic

conanfile.py, src/lib/homeobject_impl.hpp, src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_cp_callbacks.cpp, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/hs_shard_manager.cpp, src/lib/homestore_backend/replication_state_machine.cpp, src/lib/homestore_backend/replication_state_machine.hpp
=> fix calculation of pg used_bytes

conanfile.py, src/lib/homestore_backend/hs_http_manager.cpp, src/lib/homestore_backend/hs_http_manager.hpp
The routes removed must be defined in SM
=> move valid http routes to SM

conanfile.py, src/include/homeobject/homeobject.hpp, src/include/homeobject/pg_manager.hpp, src/lib/homeobject_impl.hpp, src/lib/pg_manager.cpp, src/lib/tests/PGManagerTest.cpp
Based on the API proto change, we need to add some field in HomeObject.
https://github.corp.ebay.com/SDS/nuobject_proto/pull/14/files
=> Adaptive contract change for pg move API

conanfile.py, src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/hs_shard_manager.cpp, src/lib/homestore_backend/replication_state_machine.cpp, src/lib/homestore_backend/replication_state_machine.hpp
1 add is leader checker before any raft write option
2 change `on_destroy` signature to adapt to homestore
=> add is leader checker before any raft write operation

conanfile.py, src/include/homeobject/homeobject.hpp, src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/tests/hs_repl_test_helper.hpp, src/lib/tests/fixture_app.hpp, test_package/test_package.cpp
Issue: https://github.com/eBay/HomeObject/issues/263
=> Make mem_size configurable.

conanfile.py, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_shard_manager.cpp, src/lib/homestore_backend/pg_blob_iterator.cpp, src/lib/homestore_backend/replication_state_machine.cpp, src/lib/homestore_backend/replication_state_machine.hpp, src/lib/homestore_backend/tests/homeobj_fixture.hpp, src/lib/homestore_backend/tests/hs_blob_tests.cpp
in homeobject, we have three kinds of requests that will write data(thus fetch_data might happen) to a chunk:
1 create_shard : will write a shard header to a chunk
2 seal_shard : will write a shard footer to a chunk
3 put_blob: will write user data to a chunk
for any type that writes data to a chunk, we need to handle the fetch_data request for it.
=> Implement fetch_data callback

conanfile.py, src/lib/homestore_backend/replication_state_machine.cpp
fix a memcopy issuse, we need copy the exact size of shard_super_blk，not the whole blk size
=> fix fetch data bug

conanfile.py, src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/replication_state_machine.cpp, src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
1. PG leadership stickness
2. destroy_repl_dev_listener
=> Adopt HS changes

conanfile.py, src/include/homeobject/pg_manager.hpp
add default constructor for PGStats with initialization list
=> add default constructor for PGStats with initialization list

conanfile.py, src/include/homeobject/blob_manager.hpp, src/lib/homestore_backend/hs_blob_manager.cpp, src/lib/homestore_backend/replication_state_machine.cpp
if no_space_left happens when leader call put_blob, we nee return to error to the caller
=> return no_space_left error for put_blob

conanfile.py, src/lib/blob_route.hpp, src/lib/homestore_backend/gc_manager.cpp, src/lib/homestore_backend/gc_manager.hpp, src/lib/homestore_backend/heap_chunk_selector.cpp, src/lib/homestore_backend/heap_chunk_selector.h, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/hs_shard_manager.cpp, src/lib/homestore_backend/replication_state_machine.cpp
1 when the follower receives creating shard but the pchunk of this vchunk is being gc, we need to wait until gc is completed
2 for the sake of safety, move the code , which change the vchunk state , into chunk selector so that they will be under the protection of the lock of chunkselector
3 add more detailed log , which will be helpful for debugging
=> Fix create shard

conanfile.py, src/include/homeobject/pg_manager.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/tests/homeobj_misc_tests.cpp, src/lib/homestore_backend/tests/hs_pg_tests.cpp
https://github.com/eBay/HomeObject/issues/317
=> enhance create_pg

conanfile.py, src/include/homeobject/pg_manager.hpp, src/lib/homeobject_impl.hpp, src/lib/homestore_backend/heap_chunk_selector.cpp, src/lib/homestore_backend/heap_chunk_selector.h, src/lib/homestore_backend/hs_homeobject.hpp, src/lib/homestore_backend/hs_pg_manager.cpp, src/lib/homestore_backend/tests/homeobj_fixture.hpp, src/lib/homestore_backend/tests/hs_pg_tests.cpp, src/lib/homestore_backend/tests/hs_repl_test_helper.hpp, src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp, src/lib/memory_backend/mem_homeobject.hpp, src/lib/memory_backend/mem_pg_manager.cpp, src/lib/pg_manager.cpp
In this PR:
- Improve disk lost UT.
- Provide a destroy_pg interface for upper layer to clean pg manually.
- Adapt to VChunk change. TODO will add pg_to_pdev metrics in later PR.
=> Fix error code and add destroy_pg interface

conanfile.py, src/include/homeobject/homeobject.hpp, src/lib/homestore_backend/hs_homeobject.cpp, src/lib/homestore_backend/tests/hs_repl_test_helper.hpp, src/lib/tests/fixture_app.hpp, test_package/test_package.cpp
wait until https://github.com/eBay/HomeStore/pull/809 merged
=> support get my repl_svc_port
