- src/lib/memory/blob_manager.cpp
- src/lib/memory/homeobject.hpp
- src/lib/memory/shard_manager.cpp
This is the last lock left in the MemoryHomeObject implementation. The rest are in HomeObectImpl currently.
> No need for a lock around the ShardIndex.

- conanfile.py
- src/include/homeobject/pg_manager.hpp
- src/include/homeobject/shard_manager.hpp
- src/lib/blob_manager.cpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore/CMakeLists.txt
- src/lib/homestore/homeobject.cpp
- src/lib/homestore/homeobject.hpp
- src/lib/homestore/replication_message.hpp
- src/lib/homestore/replication_state_machine.cpp
- src/lib/homestore/replication_state_machine.hpp
- src/lib/homestore/shard_manager.cpp
- src/lib/homestore/tests/CMakeLists.txt
- src/lib/homestore/tests/test_shard_manager.cpp
- src/lib/memory/shard_manager.cpp
- src/lib/pg_manager.cpp
- src/lib/shard_manager.cpp
- src/mocks/mock_replica_set.hpp
- src/mocks/repl_service.cpp
this is the draft version of create_shard implementation in homeobject and can not build successfully until ReplDev in homestore is finalized.
> SDSTOR-11601 add create_shard implementation

- src/lib/homestore/homeobject.cpp
As latest HomeStore initialize interface is changed and make HO build failed, this PR is used to adapt the new interface.
> adapt homestore initialize interface

- src/lib/blob_route.hpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore/homeobject.hpp
- src/lib/homestore/shard_manager.cpp
- src/lib/memory/homeobject.hpp
- src/lib/memory/shard_manager.cpp
@sanebay we can reuse this class and derive from BtreeKey in HomeStore (or that's the goal).
> BlobRoute : Comparison and Hash can be made much cheaper without string formatting.

- src/lib/homestore/heap_chunk_selector.cpp
- src/lib/homestore/heap_chunk_selector.h
HO will try to make all shards on same PG to be located in same HS pdev, but current HO does not know pdev id at all because pdev is managed by HS. In order to do that, we can reuse the HeapChunkSelector logic and its inner data members and add an interface which will return blk_alloc_hints for different shards on same PG.
> add interface to get blk alloc hints for chunks on same pg

- src/include/homeobject/blob_manager.hpp
- src/lib/blob_manager.cpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/tests/test_home_object.cpp
- src/lib/memory_backend/mem_homeobject.hpp
- src/lib/memory_backend/mem_shard_manager.cpp
- src/lib/shard_manager.cpp
- src/lib/tests/BlobManagerTest.cpp
Similar to create shard. 
Add test to create shard, seal and put blob and restart and verify shard is still sealed and put blob fails.
> Add seal shard api

- conanfile.py
- src/lib/CMakeLists.txt
- src/lib/homeobject_impl.cpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/tests/CMakeLists.txt
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
- src/lib/memory_backend/CMakeLists.txt
- src/lib/tests/BlobManagerTest.cpp
- src/lib/tests/CMakeLists.txt
- src/lib/tests/PGManagerTest.cpp
- src/lib/tests/ShardManagerTest.cpp
- src/lib/tests/fixture_app.cpp
- src/lib/tests/fixture_app.hpp
- test_package/test_package.cpp
The idea is to add another Executor to `iomanager` and make this one of the enumerations HSHomeObject can use which will wrap `run_on`.
> Support different Executors.

- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
there are some cases we want to mark one specific chunk as busy in heap chunk selector:
1. GC flow which will mark source chunk and dest chunk as busy to prevent more write traffic to these chunks.
2. recovery flow which may replay some create shard journal logs and need to explicitly make allocated chunk as busy
> add select specific chunk interface to heap chunk selector for recovery and GC flow

- src/lib/CMakeLists.txt
- src/lib/homeobject_impl.hpp
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_backend_config.fbs
- src/lib/homestore_backend/hs_backend_config.hpp
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/memory_backend/mem_blob_manager.cpp
- src/lib/memory_backend/mem_homeobject.hpp
We maintain a per-PG sequence number and use it to generate a blob id. This sequence number is persisted to pg metablk periodically on an iomgr user reactor by scheduling a global timer. This can be extended to trigger any other timer events in homeobject.
The blob id is generated by the leader during a put blob API and use it as a key for the call `async_alloc_write`
Testing: Added unit test to put blob after restart which will verify the persistence of the blob seq num. 
TODO:
- This PR does not handle the case when we recover from raft snapshot
- As a safety measure, a new raft leader should add a fixed value to his existing sequence number to avoid reusing blob id.
> Generate blob id from an atomic counter

- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/index_kv.hpp
some btree_kv interface and enum has been changed in HS in the following PR 
https://github.com/eBay/HomeStore/pull/211
this PR adopts the latest HS. CI will success until this PR is merged 
https://github.com/eBay/HomeStore/pull/228
> Adopt latest homestore

- conanfile.py
- src/include/homeobject/homeobject.hpp
- src/include/homeobject/pg_manager.hpp
- src/include/homeobject/shard_manager.hpp
- src/lib/homeobject_impl.cpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
- src/lib/memory_backend/mem_homeobject.hpp
- src/lib/memory_backend/mem_pg_manager.cpp
- src/lib/pg_manager.cpp
Add per PG stats according to: https://github.corp.ebay.com/SDS/nuobject_proto/pull/10
This PR will need homestore PR: https://github.com/eBay/HomeStore/pull/243/files
A new test case added for PGstats and HomeObj stats
Test:
====
```
[12/05/23 11:26:27.953] [./bin/homestore_test] [info] [82978] [hs_blob_tests.cpp:329:TestBody] stats: PGStats: id=1, replica_set_uuid=3524160a-c694-4120-9a1c-4a7626e561c2, 
num_members=3, total_shards=2, open_shards=1, avail_open_shards=127, used_bytes=26402816, avail_bytes=1676314624, 
members: 
member-1: id=9efb16ac-964d-4bc7-883c-9f8bb363839c, name=peer1, 
member-2: id=82008433-de79-4c89-bdb5-71356cb849ae, name=peer3, 
member-3: id=a75534a5-6d20-42e3-9bdc-eaa826682d2d, name=peer2
[12/04/23 12:28:17.833] [./bin/homestore_test] [info] [80734] …
```
> Issue #107 #119: HomeObject to report Per PG stats and Per-HomeObject Stats

- .jenkins/Jenkinsfile
- conanfile.py
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/memory_backend/mem_homeobject.cpp
- src/lib/tests/fixture_app.cpp
These changes are needed for the StorageManager to be built-automatically in CI and to properly use the std::optional in the public API for UUID discovery.
> We use a std::optional to indicate no uuid read.

- conanfile.py
- src/include/homeobject/pg_manager.hpp
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_message.hpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
we need to replicate create PG message across the rafte group, so that the follower can create pginfo and index table.
> replicate createpg message across raft group

- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/tests/BlobManagerTest.cpp
The delete blob test is actually deleting those blobs from putBlob, with racing with putBlobs (as we run async) and other thread(as all threads are using same blobID range for deletion).  Each deleteBlob should either success or fail with unknownBlob.
Previously we access the e.error() with out checkout !!e (success).
When success , e is folly::unit() and accessing e.error() will causing SIGABRT.
This is the reason that the UT should not pass but was pasing in the past. It is very unlikely all deleteBlob get executed before putBlob.
> UT improvement

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/tests/fixture_app.cpp
since we have restartability in homestore, enable the restartability in homeobject now
in the current implementation , when restarting, repl_dev will not be loaded when restarting meta service, it will be postponed to the the start of raft_repl_service. but when restarting, Pg is recovered when restarting metaservice , which will get the repl_dev from raft_repl_service, this causes an error.
> enable restartability for homeobject

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
recovery pg and shard after homestore is fully restarted
this io_uring problem is tracked [in this issue](https://github.com/eBay/HomeObject/issues/153)
> rework recovery

- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
in this PR, we change the shard state from open to sealed when pre_committing the seal_shard message, and change the state back to open if roll_back happens. 
but this can not fundamentally solve the conflict between seal_shard and put_blob, since when handling put_blob request, it will only check the shard state at the very beginning, and will not check again before entering raft phase(propose_to_raft). so we need a callback before appending the log where we could check the shard state again.
this should be done in homestore to provide the interfact accepting this callback
for some corner case , like we have a stale blob for shard-1 in shard-2, it will behandled by GC.
> SealShard state change in pre-commit

- conanfile.py
- src/lib/blob_manager.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
Put_blob takes `Blob&& blob` which will make the provided blob into an empty one.
In previous code we introduced retry logic for put_blob however didnt properly recreate the blob buffer which mistakenly create an empty blob with size=0.
As we only retry on not_leader and this error is not local-retryable, we dont have a case that need local retry now. It still make sense to take right value ref for blob.  Caller (now only the UT) should take responsibility to copy before call, if retry is intended.
Rejecting zero-length put will better help user to identify the error.
> Reject put_blob with zero length.

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_http_manager.cpp
Relevant changes: https://github.com/eBay/IOManager/pull/100
> Adaptive changes for HttpManager

- conanfile.py
- src/include/homeobject/shard_manager.hpp
- src/lib/blob_route.hpp
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_backend_config.fbs
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/memory_backend/mem_shard_manager.cpp
- src/lib/pg_manager.cpp
Add read_snapshot_data to go over all shards and blobs of a PG. If obj_id is zero, send all shards. obj_id is concatenation of blob sequence number and batch number. For all other values of obj_id, we send batch of blobs for a shard. Once all blobs are finished in a shard, we move to next shard_id, and batch_num is reset to 0. Add LSN in shard metadata to ignore all reads of shards which are created later that the snapshot LSN.
Added temporary code to write blobs and metadata, tested with SM long running test to create a baseline resync with follower. 
Tested with UT.
> Add baseline resync read part in homeobject.

- conanfile.py
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_http_manager.cpp
- src/lib/homestore_backend/tests/CMakeLists.txt
- src/lib/homestore_backend/tests/bits_generator.hpp
- src/lib/homestore_backend/tests/homeobj_cp_tests.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_pg_tests.cpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_homestore_backend.cpp
1 add a raft test framework for homeobject , which will enable 3-replica raft-based test.
2 move all the current UT from single replica to 3 replicas raft-based
3 find and fix a blob sequence number bug after involving the new test framework.
> raft test framework for homeobject

- conanfile.py
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
This pull request introduces the initial draft for fixing the PG size. The main work includes:
- Creating PGs based on a specified size.
- Selecting chunks from the PG's chunk heap when creating a shard.
- Related to recovery: Adapting `pg_info_superblk` to recover the state of chunkselector and the state of pg.
> implement fix pg size

- conanfile.py
- src/include/homeobject/pg_manager.hpp
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/tests/CMakeLists.txt
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/test_homestore_backend.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
this PR aims to support spare replicas in raft test framework , which is essential for testing pg move. what`s more, a basic replace_member UT is added
> support spare replicas in raft test framework

- conanfile.py
- src/include/homeobject/pg_manager.hpp
- src/include/homeobject/shard_manager.hpp
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/tests/hs_pg_tests.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
1. Implement an identical shard layout using `homestore::blk_alloc_hints`, specifically employing `pdev_id_hint` to store pg id and physical chunk id.
2. Enhance defensive checks in ChunkSelector to validate inputs and handle exceptions. Correct from r_chunk_id to p_chunk_id
3. Adapt unit tests and add `PGExceedSpaceTest`
> Shard Identical Layout

- conanfile.py
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
Fix HeapChunkSelector::get_most_available_blk_chunk
1. Add check to ensure max_it points to an available chunk.
If not, it indicates there are no available chunks left.
2. Add safeguards in the create and recover pg paths to ensure
the pg size cannot be zero.
> Fix HeapChunkSelector::get_most_available_blk_chunk

- conanfile.py
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
* Implement `ReplicationStateMachine::write_snapshot_data()` and `SnapshotReceiveHandler` logic
* Extract `local_create_pg`, `local_create_shard` and `local_add_blob_info` for follower data creation
> Implement ReplicationStateMachine::write_snapshot_data

- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
* Extract `SnapshotContext` from `SnapshotReceiveHandler` to split constant and mutable members
* Add UT for `SnapshotReceiveHandler` and fix some bugs
> Refactor SnapshotReceiveHandler & Add UT

- conanfile.py
- src/lib/homestore_backend/replication_state_machine.cpp
m_snapshot_context is nullptr in the first create_snapshot, add check to avoid crash.
> fix create_snapshot

- conanfile.py
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_pg_tests.cpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
Bug Fixes:
- Resolved issues in create_shard and seal_shard functions to ensure correct shard management. Enhancements:
- Added validation to prevent creation of placement groups with sizes smaller than the chunk size. Test Improvements:
- pg test:
- Added tests to verify that creating a placement group with a size smaller than the chunk size results in failure.
- shard test:
- Created shard but shard size is larger than pg space left which should be failed.
- Verified that successfully created shards have identical virtual chunk layouts.
> Fix and Improve `fix pg size & shard identical layout`

- conanfile.py
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
Update snapshot function name based on the [homestore API change](https://github.com/eBay/HomeStore/pull/596).
> Rename snapshot_data to snapshot_obj

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
moving PG/Shard recovery into this CB, through
HomeObject::on_replica_restart().
Stop calling on_replica_restart from StateMachine::on_restart().
> Adopt on_repl_devs_init_completed CB.

- conanfile.py
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_pg_tests.cpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_heap_chunk_selector.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
When a member is moved out of a PG, clean up the PG and reclaim resources:
1. Reset all chunk allocators and return chunks for reassignment.
2. Remove the index table associated with this PG.
3. Remove this PG from the PG map.
4. Delete the PG and its related shard metadata.
Additionally, enhance restart tests with pristine state validation, covering PG, shard, and blob tests.
> PG cleanup for moved out member

- conanfile.py
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
Enhance existing class-level UT:
* Add test for handling corrupted message
* Add verification for chunk release of sealed shards
Introduce `sisl::flip` and simulate error cases in dynamic test
> Add more UT for error cases simulated with sisl::flip

- conanfile.py
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/replication_message.hpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
This PR enhances baseline resync:
1. Address blob duplication issues caused by resync, it mainly happens when resend snapshot mesg during baseline resync and apply log after snapshot completion. This helps avoid unnecessary GC due to duplicated data. 
This mechanism is effective only for duplicated blobs. Since we do not record the blks of the `shardInfo` stored in the data service, we are unable to skip data writes for duplicated shards.
2. Reset PG and context at the beginning of the baseline resync if pg is already present.
> Baseline Resync Enhancement

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
chunk_size is not persisted in pg_sb, so set it manually during recovery.
Fix [issue24](https://docs.google.com/document/d/16DMqv9J-JuNs5c25IBuX01QXe5WbxPm4B4hAfz4JNZM/edit?tab=t.0#heading=h.pwx5p8lqreyh).
> Recover chunk_size in pg_info after restart

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
corresponding to https://github.com/eBay/HomeStore/pull/643
> purge repl dev when destroy pg

- conanfile.py
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
* Introduced a new `snp_rcvr_meta_blk` to record snapshot receiving progress on the follower. Since the `ReplicationStateMachine` instance cannot be directly referenced, the superblock is added to the `HS_PG` struct to act as a broker.
* Enabled the follower to request resumption from the beginning of a specific shard in `write_snapshot_obj`. Adjusted the cursor update handling logic to accommodate this scenario.
* Added a new test case for restarting the follower with a shorter delay to test resumption without causing a leader timeout.
> Implementation of follower-side snapshot transmission resumption

- conanfile.py
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
Commit Blocks in snapshot, or the blocks will be overwritten after restart.
Add more UTs to test logic when follower/leader restart.
> Commit Blocks in Snapshot and Enhance UT

- conanfile.py
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
Extract `get_hs_pg()/_get_hs_pg_unlock()` functions for simplicity.
> Extract get_hs_pg() function for simplicity

- conanfile.py
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
1. Introduce intervals between spawning processes to prevent conflicts when accessing config files.
This may cause the following failure
```
unknown file: Failure
C++ exception with description "[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal" thrown in SetUp().
```
2. Bump sync point num by 1000 at the start of each test case to prevent interference.
3. Remove existing `gtest_filter` argument when spawning restarted processes to ensure only the remaining test cases are executed.
------
There are still some random failures witness during local runs which seem to be caused by replica 2 getting stuck at `pg_destroy()` - so I also added some additional changes & logs to make it …
> Fix bugs in HS dynamic UT framework

- conanfile.py
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/tests/homeobj_misc_tests.cpp
Implement CRC32 hash integrity check for BlobHeader to prevent crashes caused by faults in critical fields (size/algorithm...).
> Add BlobHeader integrity validation

- conanfile.py
- src/include/homeobject/blob_manager.hpp
- src/include/homeobject/pg_manager.hpp
- src/include/homeobject/shard_manager.hpp
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
this PR add counters to record the pending request and start shutdown homestore when no pending request
> Homeobject side graceful shutdown

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/resync_pg_data.fbs
- src/lib/homestore_backend/resync_shard_data.fbs
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/homeobj_misc_tests.cpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/test_homestore_backend.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
Add statistic information to the pg meta/shard meta message.
Add metrics to track the progress.
- DonerSnapshotMetrics is in memory;
- ReceiverSnapshotMetrics persists the progress. 
Currently, use `DefaultBucket` for histogram metrics. We can refine it after the BR performance test.
> Add metrics for baseline resync

- conanfile.py
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/tests/homeobj_misc_tests.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
Previously, when a shard is empty, follower will ask for data batch 1 after handling the metadata, however the leader expect_next_obj_id will return objId for next shard, which leads to inconsistency objId.
> Handle empty shard in baseline resync

- conanfile.py
- src/include/homeobject/blob_manager.hpp
- src/include/homeobject/pg_manager.hpp
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
if leader receives a put_blob , it will increase the pending req counter. and when this put_blob is committed, it will decrease the counter. however, if rollback happens for this pub_blob , the counter will not be decreased, which will lead to hung in graceful shutdown. the same as del_blob and created_pg.
> add rollback logic for blob and pg op

- conanfile.py
- src/lib/homestore_backend/hs_pg_manager.cpp
Remove purge on pg_destroy since [purging is not supported on HS](https://github.com/eBay/HomeStore/pull/676)
> do not purge logs when pg destroy

- conanfile.py
- src/lib/homestore_backend/hs_backend_config.fbs
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
There is a side effect introduced by identical layout: After several restarts or leader switch, some garbage would cause NO_SPACE_ERROR on the follower side which leads to PG NotClean(lag and degraded) ultimately. So reserve some space in a chunk to mitigate/avoid this issue.
> Reserve space in a chunk

- conanfile.py
- src/include/homeobject/blob_manager.hpp
- src/include/homeobject/homeobject.hpp
- src/include/homeobject/pg_manager.hpp
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/index_kv.cpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_message.hpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/homeobj_misc_tests.cpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_pg_tests.cpp
- src/lib/homestore_backend/tests/hs_repl_test_helper.hpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
- src/lib/memory_backend/mem_shard_manager.cpp
- src/lib/tests/fixture_app.cpp
Standardize logging format across the codebase
- Updated all shardID logs to use the format: shardID=0x{:x},pg={},shard=0x{:x}
- Ensured all pg logs are formatted as: pg={}
- Modified all log entries to follow the key=val format for consistency
This change improves the readability and consistency of log outputs, making it easier to parse and debug.
> Enhance logging for replication machine and standardize shard_id output

- conanfile.py
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
now that we have continuous notifications of the last committed lsn, we can always set error info and wait until got the notification of this lsn is committed.
this way, we no longer need to pause statemachine and check whether the last append lsn is committed
> handling config change where we also need to check no_space_left error info

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
This pr is used to fix [SH issue48](https://docs.google.com/document/d/16DMqv9J-JuNs5c25IBuX01QXe5WbxPm4B4hAfz4JNZM/edit?tab=t.0#heading=h.8j5ij57iwi9) 
- Use a shared_ptr< PGBlobIterator >* instead of PGBlobIterator* as user_ctx to avoid freeing ctx which is being used;
- Add a lock to avoid race condition of accessing user_ctx. In `read_snapshot_obj`, only lock the part getting shared_ptr< PGBlobIterator > from the user_ctx rather than the whole read process to avoid blocking free_user_snp_ctx, because read could spend a long time while free_user_snp_ctx could be called by become_leader which should not wait for it.
- Reset cursor to the beginning when next obj id is inconsistent with the cursor. In this case, follower will validate the context lsn and reset the cursor to resume from …
> Enhance BR read_snapshot_obj

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.hpp
This change also supports larger blob sizes due to the limitation of max_blks_per_blkid
> Update blk_size from 1K to 4K to align with the physical sector size of HDDs

- conanfile.py
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
In order to provider higher queue depth for disk, which is optimal for scheduler to merge requests.
Also IO and compute(checksum) can parallel.
> Move snapshot data write to async mode.

- conanfile.py
- src/include/homeobject/shard_manager.hpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/gc_manager.cpp
- src/lib/homestore_backend/gc_manager.hpp
- src/lib/homestore_backend/heap_chunk_selector.cpp
- src/lib/homestore_backend/heap_chunk_selector.h
- src/lib/homestore_backend/hs_backend_config.fbs
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_cp_callbacks.cpp
- src/lib/homestore_backend/hs_homeobject.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/hs_shard_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/hs_blob_tests.cpp
- src/lib/homestore_backend/tests/hs_gc_tests.cpp
- src/lib/homestore_backend/tests/hs_shard_tests.cpp
- src/lib/homestore_backend/tests/test_homestore_backend.cpp
- src/lib/memory_backend/mem_shard_manager.cpp
crash recovery is also in this PR
> implement gc data copy

- conanfile.py
- src/include/homeobject/pg_manager.hpp
- src/lib/homeobject_impl.hpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/hs_pg_manager.cpp
- src/lib/homestore_backend/replication_state_machine.cpp
- src/lib/homestore_backend/replication_state_machine.hpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/test_homestore_backend_dynamic.cpp
- src/lib/memory_backend/mem_homeobject.hpp
- src/lib/memory_backend/mem_pg_manager.cpp
- src/lib/pg_manager.cpp
- src/lib/tests/PGManagerTest.cpp
This pr is the adaption change for https://github.com/eBay/HomeStore/pull/758
> Change task_id to string

- conanfile.py
- src/lib/homestore_backend/CMakeLists.txt
- src/lib/homestore_backend/hs_blob_manager.cpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
- src/lib/homestore_backend/tests/homeobj_fixture.hpp
- src/lib/homestore_backend/tests/homeobj_misc_tests.cpp
> Revert "Change BlobHeader to include user key and block_hashes."

- conanfile.py
- src/lib/homestore_backend/replication_state_machine.cpp
This pr avoids the false alarm of corrupted message when HS adds ctrl type log but HO is not updated
> Add generic handle logic for non-data-op

- conanfile.py
- src/lib/homestore_backend/gc_manager.hpp
- src/lib/homestore_backend/hs_homeobject.hpp
- src/lib/homestore_backend/pg_blob_iterator.cpp
- src/lib/homestore_backend/snapshot_receive_handler.cpp
1.for latency related metrics, change to use OpLatencyBucket
2.for percentile, use PercentileBuckets.
3.remove some unused (no observation) metrics.
> Optimize Bucket configs for Histogram
